name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-
      - name: Install dependencies
        run: npm ci
      - name: Audit dependencies
        run: npm audit --audit-level=moderate
      - name: Ensure required env vars (fail early)
        run: |
          required=(TWILIO_ACCOUNT_SID TWILIO_AUTH_TOKEN TWILIO_WHATSAPP_NUMBER)
          missing=()
          for v in "${required[@]}"; do
            if [ -z "${{ secrets.${v} }}" ] && [ -z "${!v}" ]; then
              missing+=("$v")
            fi
          done
          if [ ${#missing[@]} -ne 0 ]; then
            echo "Missing required secrets: ${missing[*]}";
            echo "Set GitHub secrets or ensure env vars are provided for CI";
            exit 1;
          fi
      - name: Set lightweight test envs
        run: |
          echo "SCHEDULING_URL=https://example.com" >> $GITHUB_ENV
          echo "DESTAPESPR_MAIN_PHONE=+17879220068" >> $GITHUB_ENV
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm test
